baseURL = "https://nmwsharp.com/recipes/"
languageCode = "en-us"
title = "Food for Thought"
publishDir = "docs"

[params]
  description = "A collection of tasty things."
  author = "Nick Sharp"
  GoogleAnalyticsUserID = "UA-58346315-1"
